language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t papannn/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true papannn/docker-react npm run test